require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.5
  EnabledByDefault: true
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'spec/{rails,spec}_helper.rb'
    - 'config/**/*'
    - 'scripts/**/*'
    - 'Gemfile'
    - 'Rakefile'

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/DocumentationMethod:
  Enabled: false

Style/MissingElse:
  Enabled: false
